#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width             5
bspc config window_gap              15

bspc config split_ratio             0.50
bspc config borderless_monocle      false
bspc config single_monocle          false
bspc config gapless_monocle         false

bspc config pointer_motion_interval  5

bspc config active_border_color \#44475a
bspc config normal_border_color \#44475a
bspc config focused_border_color \#44475a
bspc config presel_feedback_color \#44475a

bspc rule -a qutebrowser state=tiled desktop='^1'
bspc rule -a Alacritty state=floating
bspc rule -a mpv state=pseudo_tiled desktop='^2'
bspc rule -a discord state=pseudo_tiled desktop='^3'
bspc rule -a Steam state=floating desktop='^4'
bspc rule -a Gimp desktop='^6'
bspc rule -a Virt-manager state=floating desktop='^5'
bspc rule -a feh state=floating
